### PR TITLE
Fix documentation typos

### PR DESCRIPTION
**Pull request by esabol**
Trivial PR to correct typos in documentation. @yanick

### CODE REVIEW

**Comment by esabol** [comment]
Anyone around to merge this? @yanick @tokuhirom

**Comment by yanick** [comment]
Yep, it's merged locally, and will be out with the next release.

**Comment by esabol** [comment]
> Yep, it's merged locally, and will be out with the next release.

Oh, ok. Shall I close this then?

**Comment by yanick** [comment]
There, pushed to master. :-)

**Pull request merged**
